
# Color the Prompt
color_my_prompt

color black '0;30'
color red '0;31'
color green '0;32'
color yellow '0;33'
color blue '0;34'
color magenta '0;35'
color cyan '0;36'
color white '0;37'
color BLACK '1;30'
color RED '1;31'
color GREEN '1;32'
color YELLOW '1;33'
color BLUE '1;34'
color MAGENTA '1;35'
color CYAN '1;36'
color WHITE '1;37'
color endcolor ''


# keep computer awake when lid is closed 
stayawake
# Go to working directory
cd ~/Documents/root/